### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aihimel** [muntasir-billah/open_judge#9]
Please update the license file to **GPLv3** or later.

**Comment by muntasir-billah** [comment]
Thanks :)

**Comment by aihimel** [comment]
I can do it if you add me as a contributor.

**Comment by muntasir-billah** [comment]
OK

**Comment by muntasir-billah** [comment]
I've added you as a collaborator. Will that do?

> On Jan 18 2016, at 11:30 am, Muntasir Billah Munna

**Comment by aihimel** [comment]
Yes, that will do. I have already updated the license to GPLv3 and closing this issue.
